@startuml
title Causal Loop Diagram: Value Delivery System

!include ../templates/puml-theme-stickies.puml

skinparam backgroundColor white
skinparam linetype disabled

Boundary(core, "core elements") {
	Sticky(customer_satisfaction, "Customer Satisfaction Rate", "The business goal of the organization.")
  Sticky(alignment_to_market, "Alignment between product and customer needs", "The degree to which the product meets the needs of the customer.")
  Sticky(loop_length, "Length of the feedback loop", "The time it takes to get feedback from the customer.")

   alignment_to_market -left-> customer_satisfaction: " "
   loop_length -up-> alignment_to_market: "O"
}

'Boundary(organizational, "organizational elements") {
	Sticky(adaptability, "Ability to rapidly change what we're working on", "The organization's ability to quickly change direction, also known as 'adaptability' or 'business agility'.")
	Sticky(scope, "Commited scope, agreement on batch size", "The organization's promise on what they will be delivering, and how large the increments will be.")
  Sticky(complexity, "Organizational Complexity", "The amount of different divisions within the company, the existence of prescriptive processes, and the decision-making mechanism that are in place.")
  Sticky(handovers, " # of Handovers", "The number of times a piece of work is handed over from one team to another.")
  Sticky(lead_time, "Lead Time", "The time it takes to deliver a piece of work from start (concept) to finish (delivered value in hands of end-users.")
'}

adaptability -left-> alignment_to_market
handovers -right-> adaptability : "O"
scope -left-> adaptability : "O"
complexity -right-> handovers
handovers -up-> lead_time
lead_time -up-> loop_length

@enduml