@startuml
title Causal Loop Diagram: Chickens, Eggs, and Road Crossings

!include ../templates/puml-theme-stickies.puml

skinparam backgroundColor white
skinparam linetype        ortho

Sticky(eggs, " # Eggs")
Sticky(chickens, " # Chickens")
Sticky(roadCrossings, " # Road \n Crossings")

eggs -> chickens: " "
chickens -> eggs: " "
chickens -> roadCrossings: " "
roadCrossings [´]-> chickens: "O"

@enduml