@startuml
title Causal Loop Diagram: Project versus Product

!include ../templates/puml-theme-stickies.puml

skinparam backgroundColor white
skinparam linetype disabled
skinparam dpi 220

left to right direction

'Boundary(core, "core elements") {
	Sticky(customer_satisfaction, "Customer Satisfaction Rate", "The business goal of the organization.")
  Sticky(alignment_to_market, "Alignment between product and customer needs", "The degree to which the product meets the needs of the customer.")
  Sticky(loop_length, "Length of the feedback loop", "The time it takes to get feedback from the customer.")

 alignment_to_market -up-> customer_satisfaction: " "
  loop_length -left-> alignment_to_market: "O"
'}

'Boundary(organizational, "organizational elements") {
	Sticky(adaptability, "Ability to rapidly change what we're working on", "The organization's ability to quickly change direction, also known as 'adaptability' or 'business agility'.")
	Sticky(scope, "Commited scope, agreement on batch size", "The organization's promise on what they will be delivering, and how large the increments will be.")
  Sticky(complexity, "Organizational Complexity", "The amount of different divisions within the company, the existence of prescriptive processes, and the decision-making mechanism that are in place.")
  Sticky(handovers, " # of Handovers", "The number of times a piece of work is handed over from one team to another.")
  Sticky(lead_time, "Lead Time", "The time it takes to deliver a piece of work from start (concept) to finish (delivered value in hands of end-users.")
'}

'Boundary(timeliness, "timeliness elements") {
	Sticky(deadline, "Time pressure", "A type of psychological stress that occurs when there is less (perceived) time available than is required to complete a task.")
	Sticky(quality, "Quality", "The build quality of the delivered artifacts. (e.g. Maintainability, lack of technical debt, lack of defects)")
	Sticky(ownership, "Ownership", "The feeling of responsibility for the product by the team that is working on it.")
	Sticky(team_stability, "Team Stability", "How fixed / temporary people are part of the team.")
	Sticky(e2e_agency, "End-to-end agency", "Ability to deliver value independently.")
'}

'Boundary(risks, "risk mitigation elements") {
together {
	Sticky(bus_validation, "  # Inspection Opportunities", "Amount of chances to validate the business cases the organization is working to support/enable.")
	Sticky(overrun, "Risk of overruns", "The risk of a delivery costing significantly more than what we were initially willing to invest in it. (Sunk Cost)")
	Sticky(risk_avoidance, "Risk Avoidance", "Focusing on avoiding risks, rather than delivering valuable features. Favouring output over outcome. (e.g. scope negotiation, risk management, politics, window dressing)")
}
	Sticky(training, "Onboarding / Offboarding cost", "Additional effort required to bring new team members up to speed, or to ensure a smooth transition when team members leave.")
'}



adaptability --> alignment_to_market
handovers --> adaptability : "O"
scope --> adaptability : "O"
complexity --> handovers
handovers --> lead_time
lead_time --> loop_length

quality --> lead_time : "O"
deadline --> quality : "O"
e2e_agency --> ownership
e2e_agency --> handovers : "O"
ownership --> quality
team_stability --> ownership
complexity --> e2e_agency : "O"

loop_length --> bus_validation : "O"
'loop_length -[hidden]-> bus_validation
bus_validation --> alignment_to_market

bus_validation --> overrun : "O"
overrun --> risk_avoidance
deadline --> risk_avoidance
risk_avoidance --> adaptability: "O"

team_stability --> training: "O"

@enduml