@startuml
title Causal Loop Diagram: Chickens, Eggs, and Roads

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam nodesep 62
skinparam ranksep 42
skinparam dpi 164
skinparam maxMessageSize 224

skinparam wrapWidth 480

skinparam Padding 4

skinparam shadowing true
skinparam Font monospaced
skinparam defaultTextAlignment left

skinparam linetype ortho

hide stereotypes

System(eggs, "# Eggs", "")
System(chickens, "# Chickens", "")
System(roadCrossings, "# Road Crossings", "")

eggs -> chickens: " "
chickens -> roadCrossings: " "
roadCrossings -> chickens: "O"
chickens -> eggs: " "

@enduml