@startuml
title Causal Loop Diagram: Chickens, Eggs, and Roads

!include ./templates/puml-theme-stickies.puml

'System(eggs, "# Eggs", "")
'System(chickens, "# Chickens", "")
'System(roadCrossings, "# Road Crossings", "")

Sticky(eggs, "Eggs")

'eggs -> chickens: " "
'chickens -> roadCrossings: " "
'roadCrossings -> chickens: "O"
'chickens -> eggs: " "

@enduml